spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

url:
  base: https://dev.mouda.site

oauth:
  kakao:
    redirect-uri: https://dev.mouda.site/oauth/kakao
  google:
    client-secret: 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
    redirect-uri: https://dev.mouda.site/oauth/google
  apple:
    redirect-uri: https://api.dev.mouda.site/v1/auth/apple
    redirection: https://dev.mouda.site/oauth/apple?token=

aws:
  region:
    static: ap-northeast-2
  s3:
    bucket: techcourse-project-2024
    key-prefix: mouda/dev/asset/profile/
    prefix: https://dev.mouda.site/profile/

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      show-details: always
