spring:
  profiles:
    active:
      - local

security:
  jwt:
    token:
      secret-key: kksangdolbabokksangdolbabokksangdolbabokksangdolbabokksangdolbabokksangdolbabo
      expire-length: 3600000
