spring:
  application:
    name: backend
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

oauth:
  kakao:
    redirect-uri: http://localhost:8081/oauth/kakao
  google:
    client-secret: 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
    redirect-uri: http://localhost:8081/oauth/google
  apple:
    redirect-uri: https://api.dev.mouda.site/v1/auth/apple
    redirection: https://dev.mouda.site/oauth/apple?token=

aws:
  region:
    static: ap-northeast-2
  s3:
    bucket: techcourse-project-2024
    key-prefix: mouda/dev/asset/profile/
    prefix: https://dev.mouda.site/profile/

url:
  base: http://localhost:8081

management:
  metrics:
    enable:
      tomcat: true
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
server:
  tomcat:
    mbeanregistry:
      enabled: true
