spring:
  profiles:
    active:
      - local

security:
  jwt:
    token:
      secret-key: kksangdolbabokksangdolbabokksangdolbabokksangdolbabokksangdolbabokksangdolbabo
      expire-length: 3600000

app:
  firebase-config-file: serviceAccountKey.json

oauth:
  kakao:
    redirect-uri: http://localhost:8081/kakao-o-auth
