name: cd-dev

on:
  push:
    branches:
      - develop-backend

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: change permission
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/2024-mouda

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Compose up
        run: |
          docker compose -f ./backend/docker-compose.yml down mouda-be
          docker compose -f ./backend/docker-compose.yml pull mouda-be
          docker compose -f ./backend/docker-compose.yml up -d mouda-be
